### ISSUE TITLE
white page.. TypeError..

### ISSUE THREAD

**Issue by 7flash** [thirdweb-example/vite-typescript-starter#2]
![image](https://user-images.githubusercontent.com/4569866/173753246-a4939809-09a6-4ce9-a6a5-9afc48042186.png)

**Comment by jarrodwatts** [comment]
Had some issues with the most recent versions of our SDK being compatible with Vite.

I've made this example use versions that are compatible to get rid of this error, thanks for raising it @7flash.

*sorry for the delay in response. I am now watching this repo on GitHub so should get notifications in the future!*
